<?php

namespace App\Domain\Trading;

use App\Domain\Wallets\WalletService;
use App\Models\PoolAllocation;
use App\Models\TradingPool;
use App\Models\TradingSession;
use App\Models\User;
use App\Models\Wallet;
use App\Support\ChartSeries;
use App\Support\PlatformSettings;
use Carbon\CarbonImmutable;
use Illuminate\Support\Facades\DB;

/**
 * Custodial trading engine.
 *
 * Users allocate JIWA into a shared pool; the pool bot "trades" live market
 * data (Binance) on the platform's major currency pairs and its daily result
 * (positive or negative) is exactly what produces the daily investment
 * returns. Market candles for a completed UTC day are immutable, so a settled
 * day is reproducible and re-running a day never double credits.
 */
class TradingBotService
{
    public const STRATEGY_VERSION = 'v2';

    public function __construct(
        protected WalletService $walletService,
        protected MarketDataClient $marketData,
    ) {}

    /**
     * Get the platform-wide trading pool, creating the default one lazily the
     * first time the product is used.
     */
    public function pool(): TradingPool
    {
        $pool = TradingPool::query()
            ->orderBy('id')
            ->first();

        if ($pool) {
            return $pool;
        }

        return TradingPool::create([
            'name' => PlatformSettings::config('jiwa.trading_pool_name'),
            'symbol' => PlatformSettings::config('jiwa.trading_symbol'),
            'currency' => 'USD',
            'base_nav' => PlatformSettings::config('jiwa.trading_base_nav'),
            'nav' => PlatformSettings::config('jiwa.trading_base_nav'),
            'min_allocate' => PlatformSettings::config('jiwa.trading_min_allocate'),
            'max_allocate' => PlatformSettings::config('jiwa.trading_max_allocate'),
            'description' => 'A pooled JIWA fund traded by the platform bot. Daily returns are generated by the bot\'s trading results.',
            'nav_updated_at' => now(),
            'is_active' => true,
            'is_running' => true,
        ]);
    }

    /**
     * Start/stop the bot for a pool. Stopping only pauses the booking of new
     * daily sessions; existing allocations, the live today preview, the chart,
     * and withdrawals all keep working. Restarting resumes the daily cycle.
     */
    public function setRunning(TradingPool $pool, bool $running): TradingPool
    {
        $pool->update(['is_running' => $running]);

        activity('trading')
            ->performedOn($pool)
            ->withProperties([
                'action' => $running ? 'bot_started' : 'bot_stopped',
            ])
            ->log($running ? 'Bot started' : 'Bot stopped');

        return $pool;
    }

    /**
     * Move user funds from the principal wallet into the pooled bot fund.
     * The allocation buys units at the pool's current NAV.
     */
    public function allocate(User $user, TradingPool $pool, float $amount): PoolAllocation
    {
        return DB::transaction(function () use ($user, $pool, $amount) {
            if (! $pool->is_active) {
                throw new \InvalidArgumentException('The bot fund is not accepting allocations right now.');
            }

            $min = max((float) PlatformSettings::config('jiwa.trading_min_allocate'), (float) $pool->min_allocate);

            if ($amount < $min) {
                throw new \InvalidArgumentException("Minimum allocation is \${$min}.");
            }

            $max = PlatformSettings::config('jiwa.trading_max_allocate') ?? $pool->max_allocate;

            if ($max !== null && $amount > (float) $max) {
                throw new \InvalidArgumentException('Maximum allocation is $'.number_format((float) $max, 2).'.');
            }

            $alreadyAllocated = (float) $user->poolAllocations()
                ->where('pool_id', $pool->id)
                ->where('status', PoolAllocation::STATUS_ACTIVE)
                ->get()
                ->reduce(fn ($carry, $a) => $carry + $a->currentValue((float) $pool->nav), 0.0);

            if ($max !== null && ($alreadyAllocated + $amount) > (float) $max) {
                throw new \InvalidArgumentException(
                    'Total allocation limit is $'.number_format((float) $max, 2).'; this would exceed it.'
                );
            }

            $principal = $this->walletService->getOrCreate($user, Wallet::TYPE_PRINCIPAL);

            if ((float) $principal->balance < $amount) {
                throw new \InvalidArgumentException('Insufficient principal wallet balance.');
            }

            $units = (float) $pool->nav > 0 ? $amount / (float) $pool->nav : $amount / max((float) $pool->base_nav, 1);

            $this->walletService->debit(
                $principal,
                $amount,
                "Allocated to {$pool->name}",
                null,
                allowLocked: true,
            );

            $allocation = PoolAllocation::create([
                'pool_id' => $pool->id,
                'user_id' => $user->id,
                'units' => $units,
                'settled_amount' => $amount,
                'status' => PoolAllocation::STATUS_ACTIVE,
                'allocated_at' => now(),
            ]);

            $pool->increment('total_units', $units);

            activity('trading')
                ->performedOn($allocation)
                ->causedBy($user)
                ->withProperties([
                    'action' => 'pool_allocated',
                    'amount' => $amount,
                    'units' => round($units, 8),
                    'nav' => (float) $pool->nav,
                ])
                ->log('Funds allocated to bot fund');

            return $allocation;
        });
    }

    /**
     * Release funds back from the pool. The value is returned to the user's
     * earnings wallet (immediately withdrawable). Units are sold at NAV; if
     * the entire position is closed the allocation is marked closed.
     */
    public function withdraw(User $user, TradingPool $pool, float $amount, string $destination = Wallet::TYPE_EARNINGS): PoolAllocation
    {
        return DB::transaction(function () use ($user, $pool, $amount, $destination) {
            $allocation = $user->poolAllocations()
                ->where('pool_id', $pool->id)
                ->where('status', PoolAllocation::STATUS_ACTIVE)
                ->orderBy('id')
                ->first();

            if (! $allocation) {
                throw new \InvalidArgumentException('You have no active allocation in this bot fund.');
            }

            $value = $allocation->currentValue((float) $pool->nav);

            if ($amount <= 0 || $amount > $value) {
                throw new \InvalidArgumentException(
                    'Invalid amount — you can withdraw up to $'.number_format($value, 2).'.'
                );
            }

            $unitsOut = (float) $pool->nav > 0 ? $amount / (float) $pool->nav : 0;
            $remainingUnits = (float) $allocation->units - $unitsOut;

            if ($remainingUnits > 0.00000001) {
                $allocation->update([
                    'units' => $remainingUnits,
                    // Profit (or loss) rides in the unit price; shrink the
                    // settled base so the next daily settlement is correct.
                    'settled_amount' => max((float) $allocation->settled_amount * ($remainingUnits / (float) $allocation->units), 0),
                ]);
            } else {
                $remainingUnits = 0.0;
                $allocation->update([
                    'units' => 0,
                    'status' => PoolAllocation::STATUS_CLOSED,
                    'closed_at' => now(),
                ]);
            }

            $wallet = $this->walletService->getOrCreate($user, $destination);

            $this->walletService->credit(
                $wallet,
                $amount,
                "Bot fund withdrawal — {$pool->name}",
                $allocation,
            );

            $pool->update([
                'total_units' => (float) $pool->allocations()
                    ->where('status', PoolAllocation::STATUS_ACTIVE)
                    ->sum('units'),
            ]);

            activity('trading')
                ->performedOn($allocation)
                ->causedBy($user)
                ->withProperties([
                    'action' => 'pool_withdrawn',
                    'amount' => $amount,
                    'units' => round($unitsOut, 8),
                    'nav' => (float) $pool->nav,
                ])
                ->log('Funds withdrawn from bot fund');

            return $allocation;
        });
    }

    /**
     * Run the daily bot trading cycle for every pool: settle the most recent
     * completed trading day (or the explicitly provided date), move the NAV,
     * and pay each participant's daily return (generated by the bot) to their
     * earnings wallet. Profits are swept out daily so the stake stays at the
     * settled principal; losses are absorbed by the position.
     *
     * Idempotent per pool + session date.
     *
     * @return array{settled:int, paid:int, pnl:float, paused:int}
     */
    public function runDailyCycle(?CarbonImmutable $now = null): array
    {
        $now = $now ?? CarbonImmutable::today()->subDay();
        $settled = 0;
        $paid = 0;
        $pnl = 0.0;
        $paused = 0;

        $pools = TradingPool::query()->orderBy('id')->get();

        if ($pools->isEmpty()) {
            $this->pool();
            $pools = TradingPool::query()->orderBy('id')->get();
        }

        foreach ($pools as $pool) {
            if (! $pool->is_running) {
                $paused++;

                continue;
            }

            if (TradingSession::query()
                ->where('pool_id', $pool->id)
                ->where('session_date', $now->toDateString())
                ->exists()) {
                continue;
            }

            $open = (float) $pool->nav;
            $baseUnits = (float) $pool->total_units;
            $path = $this->sessionPath($pool, $now);

            DB::transaction(function () use ($pool, $now, $open, $baseUnits, $path, &$settled, &$paid, &$pnl) {
                $session = TradingSession::create([
                    'pool_id' => $pool->id,
                    'session_date' => $now->toDateString(),
                    'open_nav' => $open,
                    'high_nav' => $path['high'],
                    'low_nav' => $path['low'],
                    'close_nav' => $path['close'],
                    'return_pct' => $path['return_pct'],
                    'pnl' => ($path['close'] - $open) * $baseUnits,
                    'is_profit' => $path['is_profit'],
                    'trade_count' => $path['trade_count'],
                    'strategy' => $path['strategy'],
                ]);

                $pool->update([
                    'nav' => $path['close'],
                    'daily_return_pct' => $path['return_pct'],
                    'nav_updated_at' => $now,
                ]);

                $closeNav = $path['close'];

                $allocations = $pool->allocations()
                    ->where('status', PoolAllocation::STATUS_ACTIVE)
                    ->get();

                foreach ($allocations as $allocation) {
                    $value = $allocation->currentValue($closeNav);
                    $dayPnl = $value - (float) $allocation->settled_amount;

                    if ($dayPnl > 0) {
                        $earnings = $this->walletService->getOrCreate($allocation->user, Wallet::TYPE_EARNINGS);

                        $this->walletService->credit(
                            $earnings,
                            $dayPnl,
                            "Bot trading result — {$pool->name}",
                            $allocation,
                        );

                        // Sweep the profit out: keep the stake at its settled
                        // value and shrink the units the profit used to buy.
                        $newUnits = $closeNav > 0 ? $value / $closeNav : 0;

                        $allocation->update([
                            'units' => $newUnits,
                            'settled_amount' => $value,
                        ]);

                        $paid++;
                        $pnl += $dayPnl;
                    } else {
                        // Loss day: no payout, the NAV drop is absorbed by the
                        // position so the next settlement starts from the loss.
                        $allocation->update(['settled_amount' => $value]);
                    }
                }

                $pool->update([
                    'total_units' => (float) $pool->allocations()
                        ->where('status', PoolAllocation::STATUS_ACTIVE)
                        ->sum('units'),
                ]);

                activity('trading')
                    ->performedOn($session)
                    ->causedBy(null)
                    ->withProperties([
                        'action' => 'bot_session',
                        'symbol' => $pool->symbol,
                        'return_pct' => $path['return_pct'],
                        'open' => $open,
                        'close' => $path['close'],
                        'trades' => $path['trade_count'],
                    ])
                    ->log('Bot trading cycle settled');

                $settled++;
            });
        }

        return ['settled' => $settled, 'paid' => $paid, 'pnl' => round($pnl, 2), 'paused' => $paused];
    }

    /**
     * Real-data trading day for a pool. The strategy ("MomentumScalper") reads
     * the day's live candles for the configured strategy pair/timeframe and
     * books a damped share of the raw market move (participation factor) as
     * the pool's result, with the NAV path scaled to match so chart and
     * settlement always agree. Candle data for a completed UTC day is fixed,
     * so repeat calls for the same date produce the same path.
     *
     * @return array{open:float, high:float, low:float, close:float, return_pct:float, is_profit:bool, pnl:float, trade_count:int, strategy:string}
     */
    public function sessionPath(TradingPool $pool, CarbonImmutable $date, ?float $open = null): array
    {
        $pair = (string) PlatformSettings::config('jiwa.trading_strategy_pair');
        $interval = (string) PlatformSettings::config('jiwa.trading_strategy_timeframe');
        $open = $open ?? (float) $pool->nav;

        $candles = $this->marketData->dayCandles($pair, $interval, $date);

        if (empty($candles)) {
            return [
                'open' => round($open, 8),
                'high' => round($open, 8),
                'low' => round($open, 8),
                'close' => round($open, 8),
                'return_pct' => 0.0,
                'is_profit' => false,
                'pnl' => 0.0,
                'trade_count' => 0,
                'strategy' => 'MomentumScalper '.self::STRATEGY_VERSION." — {$pair} · {$interval} (no market data)",
            ];
        }

        $closes = array_column(array_column($candles, 'y'), 3);
        $highs = array_column(array_column($candles, 'y'), 1);
        $lows = array_column(array_column($candles, 'y'), 2);

        $dayOpen = (float) array_column(array_column($candles, 'y'), 0)[0];
        $dayClose = (float) $closes[array_key_last($closes)];
        $dayHigh = (float) max($highs);
        $dayLow = (float) min($lows);

        $rawPct = $dayOpen > 0 ? (($dayClose - $dayOpen) / $dayOpen) * 100 : 0.0;
        $participation = max(0.0, (float) PlatformSettings::config('jiwa.trading_participation_pct'));
        $returnPct = round($rawPct * $participation, 4);

        $upPct = $dayOpen > 0 ? (($dayHigh - $dayOpen) / $dayOpen) * 100 : 0.0;
        $downPct = $dayOpen > 0 ? (($dayLow - $dayOpen) / $dayOpen) * 100 : 0.0;

        $tradeCount = $this->signalCount($closes);
        $strategy = 'MomentumScalper '.self::STRATEGY_VERSION.": {$pair} · {$interval}, {$tradeCount} signal".(($tradeCount === 1) ? '' : 's');

        return [
            'open' => round($open, 8),
            'high' => round($open * (1 + ($upPct * $participation) / 100), 8),
            'low' => max(0.0, round($open * (1 + ($downPct * $participation) / 100), 8)),
            'close' => round($open * (1 + $returnPct / 100), 8),
            'return_pct' => $returnPct,
            'is_profit' => $returnPct >= 0,
            'pnl' => 0.0,
            'trade_count' => $tradeCount,
            'strategy' => $strategy,
        ];
    }

    /**
     * Number of fast/slow moving-average crosses in a candle series — the
     * moment-to-moment "trades" the scalper closes during a session.
     *
     * @param  array<int, float>  $closes
     */
    protected function signalCount(array $closes): int
    {
        $count = count($closes);
        $fast = collect(self::movingAverage($closes, 5))->all();
        $slow = collect(self::movingAverage($closes, 20))->all();

        $signals = 0;

        for ($i = 1; $i < $count; $i++) {
            if (! isset($fast[$i], $slow[$i], $fast[$i - 1], $slow[$i - 1])) {
                continue;
            }

            $a = $fast[$i] - $slow[$i];
            $b = $fast[$i - 1] - $slow[$i - 1];

            if (($a > 0 && $b <= 0) || ($a < 0 && $b >= 0)) {
                $signals++;
            }
        }

        return max($signals, 1);
    }

    /**
     * Simple moving average aligned to the source index; null until the window
     * is saturated.
     *
     * @param  array<int, float>  $values
     * @return array<int, float|null>
     */
    protected static function movingAverage(array $values, int $period): array
    {
        $out = [];
        $window = [];
        $sum = 0.0;

        foreach ($values as $i => $value) {
            $window[] = (float) $value;
            $sum += (float) $value;

            if (count($window) > $period) {
                $sum -= array_shift($window);
            }

            $out[$i] = count($window) === $period ? $sum / $period : null;
        }

        return $out;
    }

    /**
     * Ticker stats for the current (unsettled) trading day: a live preview of
     * the strategy's result so far, or the settled session when the day is
     * already booked.
     *
     * @return array{open:float, high:float, low:float, price:float, change_pct:float, is_profit:bool, trades:int, strategy:string, live:bool}
     */
    public function today(TradingPool $pool): array
    {
        $today = CarbonImmutable::today();

        $session = $pool->sessions()->where('session_date', $today->toDateString())->first();

        if ($session) {
            return [
                'open' => round((float) $session->open_nav, 2),
                'high' => round((float) $session->high_nav, 2),
                'low' => round((float) $session->low_nav, 2),
                'price' => round((float) $session->close_nav, 2),
                'change_pct' => (float) $session->return_pct,
                'is_profit' => (bool) $session->is_profit,
                'trades' => (int) $session->trade_count,
                'strategy' => (string) $session->strategy,
                'live' => false,
            ];
        }

        $open = (float) $pool->nav;
        $path = $this->sessionPath($pool, $today, $open);
        $changePct = $open > 0 ? (($path['close'] - $open) / $open) * 100 : 0.0;

        return [
            'open' => round($path['open'], 2),
            'high' => round($path['high'], 2),
            'low' => round($path['low'], 2),
            'price' => round($path['close'], 2),
            'change_pct' => round($changePct, 4),
            'is_profit' => $changePct >= 0,
            'trades' => $path['trade_count'],
            'strategy' => $path['strategy'],
            'live' => true,
        ];
    }

    /**
     * Full ApexCharts config for the trader hub chart.
     */
    public function chartConfig(MarketDataClient $marketData, string $pair, string $interval, int $limit = 250): array
    {
        $candles = $marketData->candles($pair, $interval, $limit);

        return [
            'chart' => ['type' => 'candlestick', 'toolbar' => ['show' => false]],
            'series' => [
                ['name' => $pair, 'type' => 'candlestick', 'data' => $candles],
                ['name' => 'Trend', 'type' => 'line', 'color' => '#C8942A', 'data' => ChartSeries::swingSeries($candles)],
            ],
            'xaxis' => ['type' => 'datetime'],
            'plotOptions' => ['candlestick' => ['colors' => [
                'upward' => '#71dd37',
                'downward' => '#ff5b5b',
            ]]],
            'stroke' => ['width' => 2],
            'dataLabels' => ['enabled' => false],
            'tooltip' => ['shared' => false],
            'legend' => ['show' => false],
            'grid' => ['borderColor' => 'rgba(216,168,57,0.15)'],
        ];
    }
}
