<?php

namespace App\Domain\Trading;

use App\Domain\Wallets\WalletService;
use App\Models\PoolAllocation;
use App\Models\TradingPool;
use App\Models\TradingSession;
use App\Models\User;
use App\Models\Wallet;
use App\Support\ChartSeries;
use App\Support\PlatformSettings;
use Carbon\CarbonImmutable;
use Illuminate\Support\Facades\DB;

/**
 * Custodial trading engine.
 *
 * Users allocate JIWA into a shared pool; a simulated bot "trades" the pool
 * and its daily result (positive or negative) is exactly what produces the
 * daily investment returns. Returns are deterministic per session date, so the
 * chart and the daily payout always agree and re-running a day never double
 * credits.
 */
class TradingBotService
{
    public const STRATEGY_VERSION = 'v1';

    public function __construct(protected WalletService $walletService)
    {
    }

    /**
     * Get the platform-wide trading pool, creating the default one lazily the
     * first time the product is used.
     */
    public function pool(): TradingPool
    {
        $pool = TradingPool::query()
            ->orderBy('id')
            ->first();

        if ($pool) {
            return $pool;
        }

        return TradingPool::create([
            'name' => PlatformSettings::config('jiwa.trading_pool_name'),
            'symbol' => PlatformSettings::config('jiwa.trading_symbol'),
            'currency' => 'USD',
            'base_nav' => PlatformSettings::config('jiwa.trading_base_nav'),
            'nav' => PlatformSettings::config('jiwa.trading_base_nav'),
            'min_allocate' => PlatformSettings::config('jiwa.trading_min_allocate'),
            'max_allocate' => PlatformSettings::config('jiwa.trading_max_allocate'),
            'description' => 'A pooled JIWA fund traded by the platform bot. Daily returns are generated by the bot\'s trading results.',
            'nav_updated_at' => now(),
            'is_active' => true,
        ]);
    }

    /**
     * Move user funds from the principal wallet into the pooled bot fund.
     * The allocation buys units at the pool's current NAV.
     */
    public function allocate(User $user, TradingPool $pool, float $amount): PoolAllocation
    {
        return DB::transaction(function () use ($user, $pool, $amount) {
            if (! $pool->is_active) {
                throw new \InvalidArgumentException('The bot fund is not accepting allocations right now.');
            }

            $min = max((float) PlatformSettings::config('jiwa.trading_min_allocate'), (float) $pool->min_allocate);

            if ($amount < $min) {
                throw new \InvalidArgumentException("Minimum allocation is \${$min}.");
            }

            $max = PlatformSettings::config('jiwa.trading_max_allocate') ?? $pool->max_allocate;

            if ($max !== null && $amount > (float) $max) {
                throw new \InvalidArgumentException("Maximum allocation is \$".number_format((float) $max, 2).'.');
            }

            $alreadyAllocated = (float) $user->poolAllocations()
                ->where('pool_id', $pool->id)
                ->where('status', PoolAllocation::STATUS_ACTIVE)
                ->get()
                ->reduce(fn ($carry, $a) => $carry + $a->currentValue((float) $pool->nav), 0.0);

            if ($max !== null && ($alreadyAllocated + $amount) > (float) $max) {
                throw new \InvalidArgumentException(
                    "Total allocation limit is \$".number_format((float) $max, 2).'; this would exceed it.'
                );
            }

            $principal = $this->walletService->getOrCreate($user, Wallet::TYPE_PRINCIPAL);

            if ((float) $principal->balance < $amount) {
                throw new \InvalidArgumentException('Insufficient principal wallet balance.');
            }

            $units = (float) $pool->nav > 0 ? $amount / (float) $pool->nav : $amount / max((float) $pool->base_nav, 1);

            $this->walletService->debit(
                $principal,
                $amount,
                "Allocated to {$pool->name}",
                null,
                allowLocked: true,
            );

            $allocation = PoolAllocation::create([
                'pool_id' => $pool->id,
                'user_id' => $user->id,
                'units' => $units,
                'settled_amount' => $amount,
                'status' => PoolAllocation::STATUS_ACTIVE,
                'allocated_at' => now(),
            ]);

            $pool->increment('total_units', $units);

            activity('trading')
                ->performedOn($allocation)
                ->causedBy($user)
                ->withProperties([
                    'action' => 'pool_allocated',
                    'amount' => $amount,
                    'units' => round($units, 8),
                    'nav' => (float) $pool->nav,
                ])
                ->log('Funds allocated to bot fund');

            return $allocation;
        });
    }

    /**
     * Release funds back from the pool. The value is returned to the user's
     * earnings wallet (immediately withdrawable). Units are sold at NAV; if
     * the entire position is closed the allocation is marked closed.
     */
    public function withdraw(User $user, TradingPool $pool, float $amount, string $destination = Wallet::TYPE_EARNINGS): PoolAllocation
    {
        return DB::transaction(function () use ($user, $pool, $amount, $destination) {
            $allocation = $user->poolAllocations()
                ->where('pool_id', $pool->id)
                ->where('status', PoolAllocation::STATUS_ACTIVE)
                ->orderBy('id')
                ->first();

            if (! $allocation) {
                throw new \InvalidArgumentException('You have no active allocation in this bot fund.');
            }

            $value = $allocation->currentValue((float) $pool->nav);

            if ($amount <= 0 || $amount > $value) {
                throw new \InvalidArgumentException(
                    'Invalid amount — you can withdraw up to $'.number_format($value, 2).'.'
                );
            }

            $unitsOut = (float) $pool->nav > 0 ? $amount / (float) $pool->nav : 0;
            $remainingUnits = (float) $allocation->units - $unitsOut;

            if ($remainingUnits > 0.00000001) {
                $allocation->update([
                    'units' => $remainingUnits,
                    // Profit (or loss) rides in the unit price; shrink the
                    // settled base so the next daily settlement is correct.
                    'settled_amount' => max((float) $allocation->settled_amount * ($remainingUnits / (float) $allocation->units), 0),
                ]);
            } else {
                $remainingUnits = 0.0;
                $allocation->update([
                    'units' => 0,
                    'status' => PoolAllocation::STATUS_CLOSED,
                    'closed_at' => now(),
                ]);
            }

            $wallet = $this->walletService->getOrCreate($user, $destination);

            $this->walletService->credit(
                $wallet,
                $amount,
                "Bot fund withdrawal — {$pool->name}",
                $allocation,
            );

            $pool->update([
                'total_units' => (float) $pool->allocations()
                    ->where('status', PoolAllocation::STATUS_ACTIVE)
                    ->sum('units'),
            ]);

            activity('trading')
                ->performedOn($allocation)
                ->causedBy($user)
                ->withProperties([
                    'action' => 'pool_withdrawn',
                    'amount' => $amount,
                    'units' => round($unitsOut, 8),
                    'nav' => (float) $pool->nav,
                ])
                ->log('Funds withdrawn from bot fund');

            return $allocation;
        });
    }

    /**
     * Run the daily bot trading cycle for every pool: settle the day's session,
     * move the NAV, and pay each participant's daily return (generated by the
     * bot) to their earnings wallet. Profits are swept out daily so the stake
     * stays at the settled principal; losses are absorbed by the position.
     *
     * Idempotent per pool + session date.
     *
     * @return array{settled:int, paid:int, pnl:float}
     */
    public function runDailyCycle(CarbonImmutable $now = null): array
    {
        $now = $now ?? CarbonImmutable::now();
        $settled = 0;
        $paid = 0;
        $pnl = 0.0;

        $pools = TradingPool::query()->orderBy('id')->get();

        if ($pools->isEmpty()) {
            $this->pool();
            $pools = TradingPool::query()->orderBy('id')->get();
        }

        foreach ($pools as $pool) {
            if (TradingSession::query()
                ->where('pool_id', $pool->id)
                ->where('session_date', $now->toDateString())
                ->exists()) {
                continue;
            }

            $open = (float) $pool->nav;
            $baseUnits = (float) $pool->total_units;
            $path = $this->dayPath($pool, $now);

            DB::transaction(function () use ($pool, $now, $open, $baseUnits, $path, &$settled, &$paid, &$pnl) {
                $session = TradingSession::create([
                    'pool_id' => $pool->id,
                    'session_date' => $now->toDateString(),
                    'open_nav' => $open,
                    'high_nav' => $path['high'],
                    'low_nav' => $path['low'],
                    'close_nav' => $path['close'],
                    'return_pct' => $path['return_pct'],
                    'pnl' => ($path['close'] - $open) * $baseUnits,
                    'is_profit' => $path['is_profit'],
                    'trade_count' => $path['trade_count'],
                    'strategy' => $path['strategy'],
                ]);

                $pool->update([
                    'nav' => $path['close'],
                    'daily_return_pct' => $path['return_pct'],
                    'nav_updated_at' => $now,
                ]);

                $closeNav = $path['close'];

                $allocations = $pool->allocations()
                    ->where('status', PoolAllocation::STATUS_ACTIVE)
                    ->get();

                foreach ($allocations as $allocation) {
                    $value = $allocation->currentValue($closeNav);
                    $dayPnl = $value - (float) $allocation->settled_amount;

                    if ($dayPnl > 0) {
                        $earnings = $this->walletService->getOrCreate($allocation->user, Wallet::TYPE_EARNINGS);

                        $this->walletService->credit(
                            $earnings,
                            $dayPnl,
                            "Bot trading result — {$pool->name}",
                            $allocation,
                        );

                        // Sweep the profit out: keep the stake at its settled
                        // value and shrink the units the profit used to buy.
                        $newUnits = $closeNav > 0 ? $value / $closeNav : 0;

                        $allocation->update([
                            'units' => $newUnits,
                            'settled_amount' => $value,
                        ]);

                        $paid++;
                        $pnl += $dayPnl;
                    } else {
                        // Loss day: no payout, the NAV drop is absorbed by the
                        // position so the next settlement starts from the loss.
                        $allocation->update(['settled_amount' => $value]);
                    }
                }

                $pool->update([
                    'total_units' => (float) $pool->allocations()
                        ->where('status', PoolAllocation::STATUS_ACTIVE)
                        ->sum('units'),
                ]);

                activity('trading')
                    ->performedOn($session)
                    ->causedBy(null)
                    ->withProperties([
                        'action' => 'bot_session',
                        'symbol' => $pool->symbol,
                        'return_pct' => $path['return_pct'],
                        'open' => $open,
                        'close' => $path['close'],
                        'trades' => $path['trade_count'],
                    ])
                    ->log('Bot trading cycle settled');

                $settled++;
            });
        }

        return ['settled' => $settled, 'paid' => $paid, 'pnl' => round($pnl, 2)];
    }

    /**
     * Deterministic trading day: seeded from the pool + session date, so the
     * live chart preview and the eventual settlement are always identical.
     *
     * @return array{open:float, high:float, low:float, close:float, return_pct:float, is_profit:bool, pnl:float, trade_count:int, strategy:string}
     */
    public function dayPath(TradingPool $pool, CarbonImmutable $date, float $open = null): array
    {
        $open = $open ?? (float) $pool->nav;

        $avg = (float) PlatformSettings::config('jiwa.trading_avg_daily_return_pct');
        $vol = (float) PlatformSettings::config('jiwa.trading_daily_volatility_pct');
        $lossPct = (float) PlatformSettings::config('jiwa.trading_loss_probability');

        $seed = crc32($date->toDateString().'|'.$pool->id.'|'.self::STRATEGY_VERSION);
        mt_srand($seed);

        $draw = mt_rand(0, 999) / 1000;
        $sign = $draw < $lossPct ? -1 : 1;

        $spread = $avg + $vol;
        $returnPct = $sign * round(mt_rand(20, 1000) / 1000 * $spread, 4);

        // Float back toward the average on light days so the drift reads as a
        // credible long-run performance without looking artificial.
        if ($sign > 0 && $returnPct < $avg) {
            $returnPct = round($avg - (mt_rand(0, 500) / 1000) * $vol * 0.4, 4);
        }
        $returnPct = max($returnPct, -$spread);

        $close = $open * (1 + $returnPct / 100);

        $wick = $open * ($vol / 100) * (0.3 + mt_rand(0, 700) / 1000);
        $high = max($open, $close) + $wick * (0.6 + mt_rand(0, 400) / 1000);
        $low = max(0.0, min($open, $close) - $wick * (0.6 + mt_rand(0, 400) / 1000));

        $tradeCount = mt_rand(9, 27);
        $wins = $sign > 0 ? ceil($tradeCount * (0.62 + mt_rand(0, 300) / 1000)) : floor($tradeCount * (0.38 + mt_rand(0, 200) / 1000));

        $strategy = "GridScalper ".self::STRATEGY_VERSION.": {$tradeCount} trades, {$wins} closed in profit";

        return [
            'open' => round($open, 8),
            'high' => round($high, 8),
            'low' => round($low, 8),
            'close' => round($close, 8),
            'return_pct' => $returnPct,
            'is_profit' => $sign > 0,
            'pnl' => 0.0,
            'trade_count' => $tradeCount,
            'strategy' => $strategy,
        ];
    }

    /**
     * Candles for the trader chart: one candle per settled session with a
     * live "today" candle preview when the daily session has not settled yet.
     * The live candle uses the exact deterministic path the bot will settle.
     *
     * @return array<int, array{x:int, y:array{0:float,1:float,2:float,3:float}}>
     */
    public function chartCandles(TradingPool $pool, int $days = 120): array
    {
        $sessions = $pool->sessions()
            ->orderByDesc('session_date')
            ->limit($days)
            ->get()
            ->reverse()
            ->values();

        $candles = $sessions->map(fn (TradingSession $s) => [
            'x' => $s->session_date->startOfDay()->addHours(12)->getTimestampMs(),
            'y' => [
                round((float) $s->open_nav, 2),
                round((float) $s->high_nav, 2),
                round((float) $s->low_nav, 2),
                round((float) $s->close_nav, 2),
            ],
        ])->all();

        $today = CarbonImmutable::today();

        $hasToday = $sessions->first()?->session_date->isToday();

        if (! $hasToday) {
            $open = $sessions->isNotEmpty()
                ? (float) $sessions->last()->close_nav
                : (float) $pool->nav;

            $path = $this->dayPath($pool, $today, $open);

            $candles[] = [
                'x' => $today->startOfDay()->addHours(12)->getTimestampMs(),
                'y' => [
                    round($path['open'], 2),
                    round($path['high'], 2),
                    round($path['low'], 2),
                    round($path['close'], 2),
                ],
            ];
        }

        return $candles;
    }

    /**
     * Ticker stats for the current (unsettled) trading day.
     *
     * @return array{open:float, price:float, change_pct:float, is_profit:bool, trades:int, strategy:string, live:bool}
     */
    public function today(TradingPool $pool): array
    {
        $today = CarbonImmutable::today();

        $session = $pool->sessions()->where('session_date', $today->toDateString())->first();

        if ($session) {
            return [
                'open' => round((float) $session->open_nav, 2),
                'high' => round((float) $session->high_nav, 2),
                'low' => round((float) $session->low_nav, 2),
                'price' => round((float) $session->close_nav, 2),
                'change_pct' => (float) $session->return_pct,
                'is_profit' => (bool) $session->is_profit,
                'trades' => (int) $session->trade_count,
                'strategy' => (string) $session->strategy,
                'live' => false,
            ];
        }

        $open = (float) $pool->nav;
        $path = $this->dayPath($pool, $today, $open);
        $changePct = $open > 0 ? (($path['close'] - $open) / $open) * 100 : 0;

        return [
            'open' => round($open, 2),
            'high' => round($path['high'], 2),
            'low' => round($path['low'], 2),
            'price' => round($path['close'], 2),
            'change_pct' => round($changePct, 4),
            'is_profit' => $changePct >= 0,
            'trades' => $path['trade_count'],
            'strategy' => $path['strategy'],
            'live' => true,
        ];
    }

    /**
     * Full ApexCharts config for the trader hub chart.
     */
    public function chartConfig(TradingPool $pool): array
    {
        $candles = $this->chartCandles($pool);

        return [
            'chart' => ['type' => 'candlestick', 'toolbar' => ['show' => false]],
            'series' => [
                ['name' => $pool->symbol, 'type' => 'candlestick', 'data' => $candles],
                ['name' => 'Trend', 'type' => 'line', 'color' => '#C8942A', 'data' => ChartSeries::swingSeries($candles)],
            ],
            'xaxis' => ['type' => 'datetime'],
            'plotOptions' => ['candlestick' => ['colors' => [
                'upward' => '#71dd37',
                'downward' => '#ff5b5b',
            ]]],
            'stroke' => ['width' => 2],
            'dataLabels' => ['enabled' => false],
            'tooltip' => ['shared' => false],
            'legend' => ['show' => false],
            'grid' => ['borderColor' => 'rgba(216,168,57,0.15)'],
        ];
    }
}