<?php

return [
    'nav' => 'NAV (Net Asset Value) is the price of one unit of the pooled bot fund. Just like a share price, it rises when the bot makes money and falls when it loses. Your position value is your units multiplied by the NAV.',
    'units' => 'Units are your share of the pooled bot fund. When you allocate money you buy units at the current NAV. You can release (sell) them at any time at the current NAV.',
    'available_principal' => 'Available principal is how much of your deposited principal is available to allocate into the bot fund or other investments. It includes the cash in your principal wallet and the value currently deployed in the bot fund.',
    'position_value' => 'Position value is the total current value of your bot fund holding — your units multiplied by the latest NAV.',
    'today_result' => "Today's result is how much your current position would gain or lose if Today's session settled at its current price.",
    'returns_credited' => 'Returns credited is the cumulative profit the bot has already sent to your earnings wallet from settled daily sessions.',
    'net_cash_deployed' => 'Net cash deployed is the total principal you have allocated into the bot fund, minus any amount you have already released back.',
    'total_return' => 'Total return is your overall profit or loss on the bot fund, combining credited returns and unrealised gains or losses based on the current NAV.',
    'strategy' => 'Strategy is the name of the algorithm the bot used to generate the current daily result.',
    'daily_return' => 'Bot-managed daily return is the percentage change of the fund for the current day, driven by the bot\'s live market strategy. It can be positive or negative.',
    'margin_at_work' => 'This portion of your principal is currently deployed in the bot fund as trading margin. It is not spent — it is working for you and can be released back at the current NAV.',
    'pool_pl' => 'Pool P&L is the profit or loss generated by the entire pooled fund on that day, before it is distributed across all unit holders.',
    'allocation' => 'Allocation is the act of moving principal into the pooled bot fund in exchange for units at the current NAV.',
    'withdraw' => 'Withdrawal releases your units back at the current NAV and moves the value into your earnings wallet, where it becomes immediately withdrawable.',
];